VNDK_SP_LIBRARIES := \
 	android.hardware.graphics.common@1.0.so \
	android.hardware.graphics.common@1.1.so \
	android.hardware.graphics.mapper@2.0.so \
	android.hardware.graphics.mapper@2.1.so \
	android.hardware.renderscript@1.0.so \
	android.hardware.renderscript@1.0.so \
	android.hidl.memory.token@1.0.so \
	android.hidl.memory@1.0.so \
	libRSCpuRef.so \
	libRSDriver.so \
	libRS_internal.so \
	libbacktrace.so \
	libbase.so \
	libbcinfo.so \
    libblas.so \
    libc++.so \
	libcompiler_rt.so \
	libcutils.so \
	libhardware.so \
	libhidlbase.so \
	libhidlmemory.so \
	libhidltransport.so \
	libhwbinder.so \
	libhwbinder_noltopgo.so \
	libion.so \
	liblzma.so \
	libunwind.so \
	libunwindstack.so \
	libutils.so \
	libutilscallstack.so \
	libz.so \
	android.hardware.audio@2.0.so \
	android.hardware.audio@4.0.so \
	android.hardware.audio.common@2.0.so \
	android.hardware.audio.common@2.0-util.so \
	android.hardware.audio.common@4.0.so \
	android.hardware.audio.common@4.0-util.so \
	android.hardware.audio.common-util.so \
	android.hardware.audio.effect@2.0.so \
	android.hardware.audio.effect@4.0.so \
	android.hardware.camera.common@1.0.so \
	android.hardware.camera.device@1.0.so \
	android.hardware.camera.device@3.2.so \
	android.hardware.camera.device@3.3.so \
	android.hardware.camera.device@3.4.so \
	android.hardware.camera.metadata@3.2.so \
	android.hardware.camera.metadata@3.3.so \
	android.hardware.camera.provider@2.4.so \
	android.hardware.drm@1.0.so \
	android.hardware.drm@1.1.so \
	android.hardware.gatekeeper@1.0.so \
	android.hardware.power@1.0.so \
	android.hardware.power@1.1.so \
	android.hardware.power@1.2.so \
	android.hardware.radio@1.0.so \
	android.hardware.radio@1.1.so \
	android.hardware.radio@1.2.so \
	android.hardware.radio.config@1.0.so \
	android.hardware.radio.deprecated@1.0.so \
	android.hardware.soundtrigger@2.0-core.so \
	android.hardware.soundtrigger@2.0.so \
	android.hardware.soundtrigger@2.1.so \
	android.hardware.wifi@1.0.so \
	android.hardware.wifi@1.1.so \
	android.hardware.wifi@1.2.so \
	android.hardware.wifi.hostapd@1.0.so \
	android.hardware.wifi.offload@1.0.so \
	android.hardware.wifi.supplicant@1.0.so \
	android.hardware.wifi.supplicant@1.1.so \
	libprotobuf-cpp-full.so \
	libprotobuf-cpp-lite.so \
	libpuresoftkeymasterdevice.so \
	libradio_metadata.so \
	libsoftkeymasterdevice.so \
	libtinyalsa.so \
	libxml2.so
